/** ********** AUTHENTICATION ********** */
export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

/** ********** FETCH DATA CONSTANTS ********** */
export const DATA_LOADING_REQUEST = 'DATA_LOADING_REQUEST';
export const DATA_LOADING_SUCCESS = 'DATA_LOADING_SUCCESS';
export const DATA_LOADING_FAILURE = 'DATA_LOADING_FAILURE';

/** ********** CONTROL CONSTANTS ********** */
//export const CONTROL_LOADING_REQUEST = 'CONTROL_LOADING_REQUEST';
//export const CONTROL_LOADING_SUCCESS = 'CONTROL_LOADING_SUCCESS';
//export const CONTROL_LOADING_FAILURE = 'CONTROL_LOADING_FAILURE';

/** ********** MAIN CONSTANTS ********** */
//export const MAIN_LOADING_REQUEST = 'MAIN_LOADING_REQUEST';
//export const MAIN_LOADING_SUCCESS = 'MAIN_LOADING_SUCCESS';
//export const MAIN_LOADING_FAILURE = 'MAIN_LOADING_FAILURE';

/** ********** NEWS CONSTANTS ********** */
//export const NEWS_LOADING_REQUEST = 'NEWS_LOADING_REQUEST';
//export const NEWS_LOADING_SUCCESS = 'NEWS_LOADING_SUCCESS';
//export const NEWS_LOADING_FAILURE = 'NEWS_LOADING_FAILURE';

/** ********** WEB APP CONSTANTS ********** */
//export const WEB_APP_LOADING_REQUEST = 'WEB_APP_LOADING_REQUEST';
//export const WEB_APP_LOADING_SUCCESS = 'WEB_APP_LOADING_SUCCESS';
//export const WEB_APP_LOADING_FAILURE = 'WEB_APP_LOADING_FAILURE';

/** ********** AUTHENTICATION ********** */
// export const CREATE_PROJECT = "CREATE_PROJECT";
// export const UPDATE_PROJECT = "UPDATE_PROJECT";
// export const DELETE_PROJECT = "DELETE_PROJECT";
// export const GET_PROJECT = "GET_PROJECT";
// export const PROJECT_LOADING = "PROJECT_LOADING";
// export const GET_PROJECTS = "GET_PROJECTS";
// export const PROJECTS_LOADING = "PROJECTS_LOADING";

/** ********** AUTHENTICATION ********** */
// export const CREATE_TASK = "CREATE_TASK";
// export const UPDATE_TASK = "UPDATE_TASK";
// export const DELETE_TASK = "DELETE_TASK";
// export const GET_TASKS = "GET_TASKS";
// export const TASKS_LOADING = "TASKS_LOADING";
